# Generated by Django 5.0.6 on 2024-05-31 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('web_scraper', '0002_rename_user_product_favorited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='reviews',
            field=models.ManyToManyField(related_name='reviews', to='web_scraper.review'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='web_scraper.product'),
        ),
    ]
