# Generated by Django 5.0.6 on 2024-05-31 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='favorited_by',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='content',
        ),
    ]
